import type { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import './globals.css';
import Providers from './Providers';

const font = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers fontName={font}>{children}</Providers>
    </html>
  );
}
